version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: sweg_backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_PORT: ${BACKEND_PORT}
    depends_on:
      - db
    volumes:
      - backend_data:/app
      - images_data:/backend/images
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: sweg_frontend
    env_file:
      - .env
    environment:
      VITE_API_URL: http://localhost:${BACKEND_PORT}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: sweg_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posts
    volumes:
      - db_data:/var/lib/postgresql/data   # <--- persistence
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  backend_data:
  images_data:
  db_data: