version: "3.9"

services:
  backend:
    image: ghcr.io/angeloottendorfer02/sweg-social-media-app/backend:latest
    container_name: sweg_backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    volumes:
      - images_data:/backend/images
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: unless-stopped

  worker:
    image: ghcr.io/angeloottendorfer02/sweg-social-media-app/worker:latest
    container_name: sweg_worker
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    command: python resize.py
    depends_on:
      rabbitmq:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - images_data:/backend/images
    restart: unless-stopped

  frontend:
    image: ghcr.io/angeloottendorfer02/sweg-social-media-app/frontend:latest
    container_name: sweg_frontend
    env_file:
      - .env
    environment:
      VITE_API_URL: http://localhost:${BACKEND_PORT}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sweg_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: sweg_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posts
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d posts" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  images_data:
  db_data:
  rabbitmq_data:
